table dClientes
	lineageTag: 0269f12a-e3f4-48b3-9413-01d0d851407a

	column id_cliente
		dataType: string
		lineageTag: d808a394-b446-4b79-a232-24d499785936
		summarizeBy: none
		sourceColumn: id_cliente

		annotation SummarizationSetBy = Automatic

	column nombre_cliente
		dataType: string
		lineageTag: e8c53db8-bb33-4fb6-a87d-c9ff941f2df2
		summarizeBy: none
		sourceColumn: nombre_cliente

		annotation SummarizationSetBy = Automatic

	column Status = ```
			
			        --Fecha ültima compra cada cliente
			        VAR ultima_compra = CALCULATE(LASTDATE(fventas[fecha_compra]))
			        --Fecha última compra de la base de datos
			        VAR V_data_base = MAX(fventas[fecha_compra])
			        
			        VAR V_dif = V_data_base - ultima_compra
			        VAR V_clasif = SWITCH(
			                            TRUE(), 
			                            V_dif < 45,"Activo",
			                            V_dif < 90, "Hacer contacto",
			                            "Inactivo"
			                        )
			        RETURN V_clasif
			```
		lineageTag: ef3bbd66-fa7c-41c7-862d-6f9cee96d597
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Clase = ```
			
			    VAR V_media_renta = AVERAGEX(
			                                RELATEDTABLE(fventas),
			                                RELATED(dLocal[renta_anual_media])
			                            )
			    VAR V_clasif = SWITCH(
			                        TRUE(),
			                        V_media_renta < 30000, "Clase C",
			                        V_media_renta < 60000, "Clase B",
			                        "Clase A"
			                    )
			    RETURN V_clasif
			```
		lineageTag: 1fd53360-90c0-4e65-ad67-dd49b68e006a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dClientes = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\alber\Documents\Cursos Analisis de datos\Empowerdata\Dominando DAX - nivel 5\BC_DOMINANDO_DAX\Bussiness Case\Database.xlsx"), null, true),
				    dClientes_Sheet = Origen{[Item="dClientes",Kind="Sheet"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dClientes_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Tipo cambiado", [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_cliente", type text}, {"nombre_cliente", type text}})
				in
				    #"Tipo cambiado1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

