table dproducto
	lineageTag: 0b1076bf-15b2-4b2f-9daa-154f5f8e5ef8

	column id_producto
		dataType: string
		lineageTag: eab66fa9-a757-4bb4-a081-84eca398f191
		summarizeBy: none
		sourceColumn: id_producto

		annotation SummarizationSetBy = Automatic

	column descripci贸n
		dataType: string
		lineageTag: fdd765cb-4f6d-4f28-a48f-34cd1c1d045b
		summarizeBy: none
		sourceColumn: descripci贸n

		annotation SummarizationSetBy = Automatic

	column costo_producto
		dataType: int64
		formatString: 0
		lineageTag: 7c8d3272-22a3-48b8-9a0a-78decfd613c9
		summarizeBy: none
		sourceColumn: costo_producto

		annotation SummarizationSetBy = Automatic

	column precio_venta
		dataType: int64
		formatString: 0
		lineageTag: 36ae4d2f-63ca-4a8f-b1aa-b079df10c7e2
		summarizeBy: none
		sourceColumn: precio_venta

		annotation SummarizationSetBy = Automatic

	column impuesto
		dataType: double
		lineageTag: 82848f8b-a6bf-4797-af43-93f3b4952239
		summarizeBy: none
		sourceColumn: impuesto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dproducto = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\alber\Documents\Cursos Analisis de datos\Empowerdata\Dominando DAX - nivel 5\BC_DOMINANDO_DAX\BC_DOMINANDO_DAX.xlsx"), null, true),
				    dproducto_Sheet = Origen{[Item="dproducto",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(dproducto_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id_producto", type text}, {"descripci贸n", type text}, {"costo_producto", Int64.Type}, {"precio_venta", Int64.Type}, {"impuesto", type number}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegaci贸n

	annotation PBI_ResultType = Table

