table Medidas_generales
	lineageTag: 4838098e-ba66-43c2-8dc6-31dfef0660ab

	measure Facturación =
			
			SUMX(
			    fventas, fventas[qtde] * RELATED(dproducto[precio_venta])
			)
		formatString: \$\ #,0.0;-\$\ #,0.0;\$\ #,0.0
		lineageTag: 652d1f4e-fc00-42a2-a6b6-1037a6bee231

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	measure Costo = ```
			
			// Consideramos el costo del impuesto en base al total de la facturación de cada venta
			VAR v_costo_prod = 
			        SUMX(
			            fventas,
			            fventas[qtde] * RELATED(dproducto[costo_producto])
			        )
			VAR v_impuesto = 
			        SUMX(
			            fventas,
			            fventas[qtde] * RELATED(dproducto[precio_venta]) * RELATED(dproducto[impuesto])
			        )
			RETURN v_costo_prod + v_impuesto
			```
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: 31536000-5ab9-45f9-9071-75d5f22a3343

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure Ganancia = ```
			[Facturación] - [Costo] 
			```
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: 931d05fd-63a5-426d-be73-ecfb29d01ec8

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Margen Ganancia %' =
			DIVIDE(
			                             [Ganancia],
			                             [Facturación]
			                    )
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 550050f1-2be0-47c8-bf16-79ed9ff54932

	measure Ctd_pedidos = ```
			DISTINCTCOUNT(fventas[id_compra]) 
			```
		formatString: #,0
		lineageTag: f4ea0738-9bf8-438d-870b-05bf39a53265

	measure Ctd_vendida = ```
			SUM(fventas[qtde]) 
			```
		formatString: #,0
		lineageTag: ccfaf9bd-df8e-45be-8517-616384620e82

	measure Facturación_LY = ```
			
			                CALCULATE(
			                    [Facturación],
			                    DATEADD(
			                        dCalendario[Date],
			                        -1,
			                        YEAR
			                    )
			                )
			```
		formatString: 0
		lineageTag: 92923ef3-5939-4d82-a436-04a86b67af53

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Facturación_YTD =
			
			VAR V_Max_date = MAX(dCalendario[Date])
			VAR resultado = CALCULATE(
			                    [Facturación],
			                    FILTER(
			                        ALLSELECTED(dCalendario[Date]),
			                        dCalendario[Date] <= V_Max_date
			                    )
			                )
			RETURN resultado
		formatString: \$\ #,0;-\$\ #,0;\$\ #,0
		lineageTag: f9f7ff16-539b-4ba7-9c48-2cb68b95684e

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	measure Facturación_YTD_LY =
			
			VAR V_Max_date = MAX(dCalendario[Date])
			VAR resultado = CALCULATE(
			                    [Facturación_LY],
			                    FILTER(
			                        ALLSELECTED(dCalendario[Date]),
			                        dCalendario[Date] <= V_Max_date
			                    )
			                )
			RETURN resultado
		formatString: \$\ #,0;-\$\ #,0;\$\ #,0
		lineageTag: 1d09f1c5-49bd-45cc-b4d9-7503c8de106f

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	measure YoY% = DIVIDE([Facturación] - [Facturación_LY], [Facturación_LY])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		lineageTag: 1e2ed157-f2bf-4c17-a947-e26c41d6ed2a

	measure Dif_Facturación_YTD = [Facturación_YTD] - [Facturación_YTD_LY]
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: 9635ab9e-3196-4985-bd9c-86e96f94b068

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	measure Facturación_MM30 =
			AVERAGEX(
			                    DATESINPERIOD(dCalendario[Date],MAX(dCalendario[Date]),-30, DAY),
			                    [Facturación]
			                )
		formatString: \$\ #,0;-\$\ #,0;\$\ #,0
		lineageTag: bb4dda4d-e26b-4bd7-a8a2-966cb7b3810b

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	measure Comentario_MM30 = "Media móvil 30 días"
		lineageTag: d64ca511-d64c-4d16-bd97-5ac90c19fc8d

	partition Medidas_generales = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	changedProperty = Name

	annotation PBI_ResultType = Table

